// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  // siteid:'pokermenu',
  siteid: 'whitelabel',
  // menutype: "remove",
  menutype: "disable",
  api: {
    // baseUrl:'http://pixpoker.czargaming.com/',
    pokerUrl: 'http://pixpoker.czargaming.com/',
    // baseUrl: 'https://riv1.czargaming.com/',
    baseUrl: '',
    // baseUrl: 'https://pokerbo.undertesting.com/',
    login: '/api/backoffice/login',
    logout: '/api/backoffice/logout',
    verifyTwoFactor: '/api/backoffice/verifyTwoFactor',
    getConfig: '/api/backoffice/getConfig',
    getSessionData: '/api/backoffice/getSessionData',
    plrLvlNames: '/api/backoffice/getPlayerLevelsNames',
    getPlayerLevelsNames: '/api/backoffice/getPlayerLevelsNames',
    getAdmins: '/api/backoffice/getAdmins',
    setAdmin: '/api/backoffice/setAdmin',
    getAdminPermissions: '/api/backoffice/getAdminPermissions',
    setAdminPermissions: '/api/backoffice/setAdminPermissions',
    getDefaultAdminPermission: '/api/backoffice/getDefaultAdminPermission',
    sessionTouch: '/api/backoffice/sessionTouch',
    getPokerScoutStatistics: '/api/backoffice/getPokerScoutStatistics',
    getOnlineStats: '/api/backoffice/getOnlineStats',
    Reports: {
      skinReport: '/api/backoffice/skinReport',
      summaryReport: '/api/backoffice/summaryReport',
      rakeRaceReport: '/api/backoffice/rakeRaceReport',

      // getSkinsPlayersDateAggr: '/api/backoffice/getSkinsPlayersDateAggr',
      getSkinsDateAggr: '/api/backoffice/getSkinsDateAggr',

      getSkinsMoneyReport: '/api/backoffice/getSkinsMoneyReport',
      getSkinReportBySessions: '/api/backoffice/getSkinReportBySessions',
      getLeaderBoardReport: '/api/backoffice/getLeaderBoardReport',
      getPlayerRakeReport: '/api/backoffice/getPlayerRakeReport',
      getPlayerAct: '/api/backoffice/getPlayerAct',
    },
    utility :{
      setBlackListRecord:'/api/backoffice/setBlackListRecord',
      getGeoIpProvider:'/api/backoffice/getGeoIpProvider',
      setGeoIpProvider:'/api/backoffice/setGeoIpProvider',
      updateGeoIpProviderDatabase:'/api/backoffice/updateGeoIpProviderDatabase',
      getIpLocation:'/api/backoffice/getIpLocation',
      checkUserAccess:'/api/backoffice/checkUserAccess',
      setBotStrategy:'/api/backoffice/setBotStrategy',
      validateImportBotsFromCsv:'/api/backoffice/validateImportBotsFromCsv',
      createRequestedReport:'/api/backoffice/createRequestedReport',
      setCategory:'/api/backoffice/setCategory',
      sendMessageToAll:'/api/backoffice/sendMessageToAll',
      getLeaderboardPayoutTemplates:'/api/backoffice/getLeaderboardPayoutTemplates',
    },
    playerControl: {
      getPlayersSummaryByFilter: '/api/backoffice/getPlayersSummaryByFilter',
      getPlayersOnlineForGames: '/api/backoffice/getPlayersOnlineForGames',
      getAccLockedBonuses: '/api/backoffice/getAccLockedBonuses',
      getVisitStat: '/api/backoffice/getVisitStat',
      getSuspiciousPlayers: '/api/backoffice/getSuspiciousPlayers',
      setSuspiciousPlayerActive: '/api/backoffice/setSuspiciousPlayerActive',
      getBlackList: '/api/backoffice/getBlackList',
      delBlackListRecords: '/api/backoffice/delBlackListRecords',
      getBlackListAnalizer: '/api/backoffice/getBlackListAnalizer',
      getAccFraudPlayers: '/api/backoffice/getAccFraudPlayers',
      getPlayerRegistrationSettings: '/api/backoffice/getPlayerRegistrationSettings',
      getWinnersStat: '/api/backoffice/getWinnersStat',
      getLosersStat: '/api/backoffice/getLosersStat',
      getPlayerDisconnectionProtectionSetup: '/api/backoffice/getPlayerDisconnectionProtectionSetup',
      resetPlayerDisconnectionProtectionSetting: '/api/backoffice/resetPlayerDisconnectionProtectionSetting',
      getAvatarList: '/api/backoffice/getAvatarList',
      setAvatarStatus: '/api/backoffice/setAvatarStatus',
      listUserAccessRules: '/api/backoffice/listUserAccessRules',
      listUserPermissionsGroup: '/api/backoffice/listUserPermissionsGroup',


      createUserPermissionsGroup: '/api/backoffice/createUserPermissionsGroup',
      updateUserPermissionsGroup: '/api/backoffice/updateUserPermissionsGroup',
      setUserAccessRule: '/api/backoffice/setUserAccessRule',
      getUserAccessRules: '/api/backoffice/getUserAccessRules',
      setUserAccessRuleActive: '/api/backoffice/setUserAccessRuleActive',
      setPlayerRegistrationSettings: '/api/backoffice/setPlayerRegistrationSettings',

      PlayerExpolore: {
        getPlayersSummary: '/api/backoffice/getPlayersSummary',
        getPlayersPersonal: '/api/backoffice/getPlayersPersonal',
        setPlayersPersonal: '/api/backoffice/setPlayersPersonal',
        getPlayerVisibleCashWallets: '/api/backoffice/getPlayerVisbleCashWallets',
        getPlayersBalances: '/api/backoffice/getPlayersBalances',
        getCurrencyExchangeRates: '/api/backoffice/getCurrencyExchangeRates',
        setPlayerBonusAdjustment: '/api/backoffice/setPlayerBonusAdjustment',
        setPlayerCashAdjustment: '/api/backoffice/setPlayerCashAdjustment',
        adjustTournamentMoney: '/api/backoffice/adjustTournamentMoney',
        setPlayerDeposit: '/api/backoffice/setPlayerDeposit',
        getPlayerCashWallets: '/api/backoffice/getPlayerCashWallets',
        getPlayerHouseRevenue: '/api/backoffice/getPlayerHouseRevenue',
        getPlayerCashoutRequest: '/api/backoffice/getPlayerCashoutRequest',

        setPlayerTrusted: '/api/backoffice/setPlayerTrusted',
        setPlayerActive: '/api/backoffice/setPlayerActive',
        setDeclineDeposits: '/api/backoffice/setDeclineDeposits',
        reactivationFraudPlayers: '/api/backoffice/reactivationFraudPlayers',
        setPlayerChatAllowed: '/api/backoffice/setPlayerChatAllowed',
        changePlayersPermissionsGroup: '/api/backoffice/changePlayersPermissionsGroup',
        assignCompPointsLevelToPlayer: '/api/backoffice/assignCompPointsLevelToPlayer',
        setPlayerAlias: '/api/backoffice/setPlayerAlias',
        getPlayerAnalizer: '/api/backoffice/getPlayerAnalizer',
        getPlayerIpHistory: '/api/backoffice/getPlayerIpHistory',

        setPlayerMarkAsFraud: '/api/backoffice/setPlayerMarkAsFraud',
        listStoredFile: '/api/backoffice/listStoredFile',
        getStoredFileContent: '/api/backoffice/getStoredFileContent',
        delStoredDocument: '/api/backoffice/delStoredDocument',
        getPlayerComments: '/api/backoffice/getPlayerComments',
        setRemoteActivity: '/api/backoffice/setRemoteActivity',
        setPlayerDisconnectionProtectionSetup: '/api/backoffice/setPlayerDisconnectionProtectionSetup',
        setPlayerComment: '/api/backoffice/setPlayerComment',
        delPlayerComment: '/api/backoffice/delPlayerComment',
        addstoredDoc: '/api/backoffice/addStoredDocument',
        liststoredDoc: '/api/backoffice/addStoredDocument',
        getplayervisablewalletCashout: 'api/backoffice/getPlayerVisibleCashWallets',
        prepareRestrictPlayer: '/api/backoffice/prepareRestrictPlayer',
        prepareMarkAsFraud: '/api/backoffice/prepareMarkAsFraud',
        setPlayerRestrict: '/api/backoffice/setPlayerRestrict',
      }
    },
    CasinoGames: {
      getFreeGameSettings: '/api/backoffice/getFreeGameSettings',
      setFreeGameSettings: '/api/backoffice/setFreeGameSettings',
      getGameList: '/api/backoffice/getGamesList',
      getCasinoGameSessions: '/api/backoffice/getCasinoGameSessions',
      getGameRoundList: '/api/backoffice/getGameRoundList',
      getGameParametersWizardData: '/api/backoffice/getGameParametersWizardData',
      listGameParametersPresets: '/api/backoffice/listGameParametersPresets',
    },
    PokerGames: {
      pokertablegroups: '/api/backoffice/getPokerTableGroupList',
      getPokerGameSessions: '/api/backoffice/getPokerGameSessions',
      getBlindStructureList: '/api/backoffice/getBlindStructureList',
      getpokertournament: '/api/backoffice/getPokerTournamentSettings',
      getPokerSitnGo: '/api/backoffice/getPokerTournamentSettings',
      getPokerTimeoutsSettings: '/api/backoffice/getPokerTimeoutsSettings',
      setPokerTimeoutsSettings: '/api/backoffice/setPokerTimeoutsSettings',
      setPokerTournamentSeries: '/api/backoffice/setPokerTournamentSeries',
      enableTournamentSeries: '/api/backoffice/enableTournamentSeries',
      getPokerPayoutStructureList: '/api/backoffice/getPokerPayoutStructureList',
      PokerSatiliteSeries: '/api/backoffice/listPokerTournamentSeries',
      getPokerTournamentSeries: '/api/backoffice/getPokerTournamentSeries',
      listTournamentTickets: '/api/backoffice/listTournamentTickets',
      getTournamentTickets: '/api/backoffice/getTournamentTickets',
      convertTournamentTicketsToTournamentMoney: '/api/backoffice/convertTournamentTicketsToTournamentMoney',
      convertTournamentTicketsToCash: '/api/backoffice/convertTournamentTicketsToCash',
      deleteTournamentTickets: '/api/backoffice/deleteTournamentTickets',
      getPokerTableGroupList: '/api/backoffice/getPokerTableGroupList',
      getPokerRakeStructure: '/api/backoffice/getRakeStructureFilteredList',

      getPokerTableHistory: '/api/backoffice/getPokerTableHistory',
      PokerHandsHistorySession: '/api/backoffice/getPokerTournamentsHistory',
      // PokerHandsHistory: '/api/backoffice/getPokerTournamentsHistory',
      // PokerSitnGoHistory: '/api/backoffice/getPokerTournamentsHistory',
      getPokerTournamentsHistory: '/api/backoffice/getPokerTournamentsHistory',

      getRakeStructureList: '/api/backoffice/getRakeStructureList',
      setPokerTableGroup: '/api/backoffice/setPokerTableGroup',
      closePokerTable: '/api/backoffice/closePokerTable',
      setPokerTableGroupStatus: '/api/backoffice/setPokerTableGroupStatus',
      setPokerTournamentSettings: '/api/backoffice/setPokerTournamentSettings',
      enableTournament: '/api/backoffice/enableTournament',
      createBlindStructure: '/api/backoffice/createBlindStructure',
      updateBlindStructure: '/api/backoffice/updateBlindStructure',
      createRakeStructure: '/api/backoffice/createRakeStructure',
      updateRakeStructure: '/api/backoffice/updateRakeStructure',
      createPokerPayoutsStructure: '/api/backoffice/createPokerPayoutsStructure',
      updatePokerPayoutsStructure: '/api/backoffice/updatePokerPayoutsStructure',
      cancelTournament: '/api/backoffice/cancelTournament',
      continueTournament: '/api/backoffice/continueTournament',
      pauseTournament: '/api/backoffice/pauseTournament',
      getPokerHandsHistory: '/api/backoffice/getPokerHandsHistory',
      getPlayersPokerHandsHistory: '/api/backoffice/getPlayersPokerHandsHistory',
      getPokerHandHistoryDetails: '/api/backoffice/getPokerHandHistoryDetails',
      getGameTableChatHistory: '/api/backoffice/getGameTableChatHistory',
      getPokerTournamentInfo: '/api/backoffice/getPokerTournamentInfo',
      getTournamentPlayers: '/api/backoffice/getTournamentPlayers',
      getPokerTournamentTables: '/api/backoffice/getPokerTournamentTables',
      getTournamentChatHistory: '/api/backoffice/getTournamentChatHistory',
      getPokerTournamentRegistrationInfo: '/api/backoffice/getPokerTournamentRegistrationInfo',
      findPokerTournamentPlayerRegistrationCandidate: '/api/backoffice/findPokerTournamentPlayerRegistrationCandidate',
      registerTournamentPlayer: '/api/backoffice/registerTournamentPlayer',
      playerexplorer: {
        getPlayerPokerTableHistory: '/api/backoffice/getPlayerPokerTableHistory',
        getPokerTournamentPlayersHistory: '/api/backoffice/getPokerTournamentPlayersHistory',
        // getPlayersPokerHandsHistory: '/api/backoffice/getPlayersPokerHandsHistory',
        getPokerTournamentSettings: '/api/backoffice/getPokerTournamentSettings',
        createTournamentTicket: '/api/backoffice/createTournamentTicket'
      }
    },
    RemoteSystems: {
      getRemoteSystems: '/api/backoffice/getRemoteSystems',
      setRemoteSystem: '/api/backoffice/setRemoteSystem',
      getRemoteGamesList: '/api/backoffice/getRemoteGamesList',
      getRemoteGameSessions: '/api/backoffice/getRemoteGameSessions',
      getRemoteActivitySummary: '/api/backoffice/getRemoteActivitySummary',
      getRemoteActivityHistory: '/api/backoffice/getRemoteActivityHistory',
      getRemoteGameSessionActions: '/api/backoffice/getRemoteGameSessionActions',

    },
    JackPots: {
      getJackpotsList: '/api/backoffice/getJackpotsList',
      setJackpot: '/api/backoffice/setJackpot',
      getJackpotAdjustments: '/api/backoffice/getJackpotAdjustments',
      listJackpotAdjustments: '/api/backoffice/listJackpotAdjustments',
    },
    GameActivitysimulator: {
      getBotStrategiesList: '/api/backoffice/getBotStrategiesList',
      getBotsList: '/api/backoffice/getBotsList',
    },
    Promotions: {
      getLeaderboardSettings: '/api/backoffice/getLeaderboardSettings',
      getLeaderboardsList: '/api/backoffice/getLeaderboardsList',
      getPromotionalCodes: '/api/backoffice/getPromotionalCodes',
      getBounsABuse: '/api/backoffice/getBonusAbuseSettings',
      setBonusAbuseSettings: '/api/backoffice/setBonusAbuseSettings',
      getdepositbonuslimit: '/api/backoffice/getDepositBonusLimits',
      setdepositbonuslimit: '/api/backoffice/setDepositBonusLimits',
      setPlayerDepositBonusLimits: '/api/backoffice/setPlayerDepositBonusLimits',
      getPlayerDepositBonusLimits: '/api/backoffice/getPlayerDepositBonusLimits',
      setPromotionalCode: '/api/backoffice/setPromotionalCode',
      setPromotionalCodeActivity: '/api/backoffice/setPromotionalCodeActivity',
    },
    CompPoints: {
      getCompPointsLevelChangeList: '/api/backoffice/getCompPointsLevelChangeList',
      pointsettings: '/api/backoffice/getCompPointsSettings',
      setCompPointsSettings: '/api/backoffice/setCompPointsSettings',
      getCompPointsAdjustments: '/api/backoffice/getCompPointsAdjustments',
      setCompPointsAdjustment: '/api/backoffice/setCompPointsAdjustment',
      getAccPlayersCompPointsBalance: '/api/backoffice/getAccPlayersCompPointsBalance',
      getPlayerCompPointsBalances: '/api/backoffice/getPlayerCompPointsBalances',
      comppointssetting: '/api/backoffice/listCompPointsEarnSettings',
      getCompPointsEarnSettings: 'api/backoffice/getCompPointsEarnSettings',
      exchangerates: '/api/backoffice/listCompPointsExchangeRates',
      setCompPointsExchangeRates: '/api/backoffice/setCompPointsExchangeRates',
      complevel: '/api/backoffice/getCompPointsLevelsReport',
      getCompPointsExchanges: '/api/backoffice/getCompPointsExchanges',
      listCompPointsLevels: '/api/backoffice/listCompPointsLevels',
      setCompPointsEarnSettings: 'api/backoffice/setCompPointsEarnSettings',
      updateComPointsLevelsAndRecalculatePlayers: 'api/backoffice/updateCompPointsLevelsAndRecalculatePlayers',
      getCompPointsCounters: '/api/backoffice/getCompPointsCounters',
    },
    Accounting: {
      getAccCasinoBalance: '/api/backoffice/getAccCasinoBalance',
      getAccPlayersBalance: '/api/backoffice/getAccPlayersBalance',
      getGamesAccounting: '/api/backoffice/getGamesAccounting',
      getAccClubGamesBalance: '/api/backoffice/getAccClubGamesBalance',
      getAccAffWebmasterPayments: '/api/backoffice/getAccAffWebmasterPayments',
      getAccAffiliateExpense: '/api/backoffice/getAccAffiliateExpense',
      getAgentsBalance: '/api/backoffice/getAgentsBalance',
      getAgentsNestedBalance: '/api/backoffice/getAgentsNestedBalance',
      getAccAgentExpense: '/api/backoffice/getAccAgentExpense',
      getAccBotStrategiesExpences: '/api/backoffice/getAccBotStrategiesExpences',
      getAccSummary: '/api/backoffice/getAccSummary',

      playerexplorer: {
        getPlayerSummaryBalances: '/api/backoffice/getPlayerSummaryBalances',
      }
    },
    Cashier: {
      settings: {
        getMerchantSettings: '/api/backoffice/getMerchantSettings',
        setMerchantSettings: '/api/backoffice/setMerchantSettings',
        getFraudControlSettings: '/api/backoffice/getFraudControlSettings',
        setFraudControlSettings: '/api/backoffice/setFraudControlSettings',
        getCurrency: '/api/backoffice/getCurrency',
        setCurrency: '/api/backoffice/setCurrency',
        getWalletExchangeSettings: '/api/backoffice/getWalletExchangeSettings',
        setWalletExchangeSettings: '/api/backoffice/setWalletExchangeSettings',
        getDepositLimits: '/api/backoffice/getDepositLimits',
        getPlayerDepositLimits: '/api/backoffice/getPlayerDepositLimits',
        setDepositLimits: '/api/backoffice/setDepositLimits',
        getCommonTransferLimits: '/api/backoffice/getCommonTransferLimits',
        getUserTransferLimits: '/api/backoffice/getUserTransferLimits',
        getReferringSettings: '/api/backoffice/getReferringSettings',
        getPlayersReferringSettings: '/api/backoffice/getPlayersReferringSettings',
        getPlayerSettings: '/api/backoffice/getPlayerSettings',
        setPlayerSettings: '/api/backoffice/setPlayerSettings',

      },
      getCurrencyExchangeRates: '/api/backoffice/getCurrencyExchangeRates',
      getAccCashout: '/api/backoffice/getAccCashout',
      getDeposits: '/api/backoffice/getDeposits',
      getWithdrawals: '/api/backoffice/getWithdrawals',
      getChargebacks: '/api/backoffice/getChargebacks',
      getCommonPlayerTransfers: '/api/backoffice/getCommonPlayerTransfers',
      getAccBalanceAdjustment: '/api/backoffice/getAccBalanceAdjustment',
      getAccBonusAdjustment: '/api/backoffice/getAccBonusAdjustments',
      getTournamentMoneyAdjustments: '/api/backoffice/getTournamentMoneyAdjustments',

      getAgentBalanceAdjustments: '/api/backoffice/getAgentBalanceAdjustments',
      getAgentToAgentTransfers: '/api/backoffice/getAgentToAgentTransfers',
      getAgentToPlayerTransfers: '/api/backoffice/getAgentToPlayerTransfers',
      getAgentRevenuePayments: '/api/backoffice/getAgentRevenuePayments',
      getAgentRevenueAdjustment: '/api/backoffice/getAgentRevenueAdjustment',
      getWebmasterPaymentsByFilter: '/api/backoffice/getWebmasterPaymentsByFilter',
      getAffiliateRevenueAdjustment: '/api/backoffice/getAffiliateRevenueAdjustment',
      getPromotionalCodeUsages: '/api/backoffice/getPromotionalCodeUsages',
      getTransactions: '/api/backoffice/getTransactions',
      getAccFraudLosses: '/api/backoffice/getAccFraudLosses',
      listGameBankAdjustments: '/api/backoffice/listGameBankAdjustments',
      getCurrencyExchanges: '/api/backoffice/getCurrencyExchanges',
      getLeaderboardPayments: '/api/backoffice/getLeaderboardPayments',


      getAvailableCashoutDeposits: '/api/backoffice/getAvailableCashoutDeposits',
      setCashoutRequestApproveForPlayer: '/api/backoffice/setCashoutRequestApproveForPlayer',
      setCashoutRequestApproveForPlayerRiver: '/api/backoffice/setCashoutRequestApproveForPlayerRiver',
      getAvailableCashoutMeansForPlayer: '/api/backoffice/getAvailableCashoutMeansForPlayer',
      getAvailableCashoutMeansForAgent: '/api/backoffice/getAvailableCashoutMeansForAgent',
      setCashoutRequestReversal: '/api/backoffice/setCashoutRequestReversal',
      setCashoutRequestReversalRiver: '/api/backoffice/setCashoutRequestReversalRiver',
      setPlayerCompulsoryCashout: '/api/backoffice/setPlayerCompulsoryCashout',
      setFraudPaymentForPlayer: '/api/backoffice/setFraudPaymentForPlayer',
      setFraudPaymentForAgent: '/api/backoffice/setFraudPaymentForAgent',
      commitTransaction: '/api/backoffice/commitTransaction',
      rollbackTransactions: '/api/backoffice/rollbackTransactions',
      restartTransaction: '/api/backoffice/restartTransaction',

      playerexplorer: {
        getPlayerDeposits: '/api/backoffice/getPlayerDeposits',
        getPlayerCashouts: '/api/backoffice/getPlayerCashouts',
        getPlayerWithdrawals: '/api/backoffice/getPlayerWithdrawals',
        getPlayerChargebacks: '/api/backoffice/getPlayerChargebacks',
        getPlayerCashAdjustment: '/api/backoffice/getPlayerCashAdjustment',
        getPlayerBonusAdjustment: '/api/backoffice/getPlayerBonusAdjustment',
        getPlayerTournamentMoneyAdjustment: '/api/backoffice/getPlayerTournamentMoneyAdjustment',
        getPlayerCurrencyExchanges: '/api/backoffice/getPlayerCurrencyExchanges',
       
      }
    },
    AgentControl: {
      getAgentsList: '/api/backoffice/getAgentsList',
      getAgentStatistics: '/api/backoffice/getAgentStatistics',
      listUserAccessRules: '/api/backoffice/listUserAccessRules',
      getAgentRegistrationSettings: '/api/backoffice/getAgentRegistrationSettings',
      listUserPermissionsGroup: '/api/backoffice/listUserPermissionsGroup',
      makeDefaultUserPermissionsGroup: '/api/backoffice/makeDefaultUserPermissionsGroup',
      deleteUserPermissionsGroup: '/api/backoffice/deleteUserPermissionsGroup',

      getAgentGrossRevenueDefaultPercents: '/api/backoffice/getAgentGrossRevenueDefaultPercents',
      createAgent: '/api/backoffice/createAgent',
      setAgentStatus: '/api/backoffice/setAgentStatus',
      changeAgentsPermissionsGroup: '/api/backoffice/changeAgentsPermissionsGroup',

      AgentExplorer: {
        getAgentSummaryInfo: '/api/backoffice/getAgentSummaryInfo',
        setAgentsPersonal: '/api/backoffice/setAgentPersonal',

        getAgentsPersonal: '/api/backoffice/getAgentsPersonal',
        getAgentsSummaryBalance: '/api/backoffice/getAgentsSummaryBalance',
        getAgentsRevenueSummary: '/api/backoffice/getAgentsRevenueSummary',
        getAgentCashWallets: '/api/backoffice/getAgentCashWallets',
        getAgentRevenueFromPlayers: '/api/backoffice/getAgentRevenueFromPlayers',
        getAgentRevenueFromAgents: '/api/backoffice/getAgentRevenueFromAgents',
        getAgentGrossRevenuePercents: '/api/backoffice/getAgentGrossRevenuePercents',
        setGrossRevenuePercents: '/api/backoffice/setGrossRevenuePercents',
        getAgentVisibleCashWallets: '/api/backoffice/getAgentVisibleCashWallets',
        getAgentsBalances: '/api/backoffice/getAgentsBalances',
        setAgentBalanceAdjustment: '/api/backoffice/setAgentBalanceAdjustment',
        getAgentChargebacksForReferredPlayers: '/api/backoffice/getAgentChargebacksForReferredPlayers',
        getAgentIpHistory: '/api/backoffice/getAgentIpHistory',
        setLinkStatusBetweenAgentAndPlayer: '/api/backoffice/setLinkStatusBetweenAgentAndPlayer',
        setLinkStatusBetweenAgentAndAgent: '/api/backoffice/setLinkStatusBetweenAgentAndAgent',
        createTransferBetweenAgents: '/api/backoffice/createTransferBetweenAgents',
        createTransferBetweenAgentAndPlayer: '/api/backoffice/createTransferBetweenAgentAndPlayer',
        getAgentCampaigns: '/api/backoffice/getAgentCampaigns',
        getUserByLogin: '/api/backoffice/getUserByLogin',
        referPlayerByAgent: '/api/backoffice/referPlayerByAgent',
        makeAgentWalletPreferred: '/api/backoffice/makeAgentWalletPreferred',
        referAgentByAgent: '/api/backoffice/referAgentByAgent',
        makePaymentForAgents: '/api/backoffice/makePaymentForAgents',
        getAgentDeposits: '/api/backoffice/getAgentDeposits',
        getAgentCurrencyExchanges: '/api/backoffice/getAgentCurrencyExchanges',
        getAgentCreditBacks: '/api/backoffice/getAgentCreditBacks', 
        getAgentChargebacks: '/api/backoffice/getAgentChargebacks', 
        getAgentCashouts: '/api/backoffice/getAgentCashouts',
        setAgentRegistrationSettings: '/api/backoffice/setAgentRegistrationSettings',
        getDetailedTransactionHistory: '/api/backoffice/getDetailedTransactionHistory',
      }
    },
    AffiliateControl: {
      Affiliateslist: '/api/backoffice/getWMasterSummaryInfoByFilter',
      getWMasterStatistics: '/api/backoffice/getWMasterStatistics',
      listUserAccessRules: '/api/backoffice/listUserAccessRules',
      getWebmasterRegistrationSettings: '/api/backoffice/getWebmasterRegistrationSettings',
      createWMaster: '/api/backoffice/createWMaster',
    },
    Tools: {
      getMailTemplatesByType: '/api/backoffice/getMailTemplatesByType',
      getWmMailingList: '/api/backoffice/getWmMailingList',
      getMailingList: '/api/backoffice/getMailingList',
      sendWmMail: '/api/backoffice/sendWmMail',
      getBonusMailingList: '/api/backoffice/getBonusMailingList',
      sendBonusListMail: '/api/backoffice/sendBonusListMail',
      sendMail: '/api/backoffice/sendMail',
      changeMailingListRecordState: '/api/backoffice/changeMailingListRecordState',
      getCategories: '/api/backoffice/getCategories',
      delCategory: '/api/backoffice/delCategory',
      getNewsList: '/api/backoffice/getNewsList',
      getNews: '/api/backoffice/getNews',
      setNews: '/api/backoffice/setNews',
      publishNews: '/api/backoffice/publishNews',
      deleteNews: '/api/backoffice/deleteNews',
      archiveNews: '/api/backoffice/archiveNews',
      getActiveQueries: '/api/backoffice/getActiveQueries',
      getMailTemplates: '/api/backoffice/getMailTemplates',
      setMailTemplate: '/api/backoffice/setMailTemplate',
      delMailTemplates: '/api/backoffice/delMailTemplates',
      getMailTemplateParameters: '/api/backoffice/getMailTemplateParameters',
      getMailTemplateText: '/api/backoffice/getMailTemplateText',
      getMailingSettings: '/api/backoffice/getMailingSettings',
    },
    RequestedReports: {
      getRequestedReports: '/api/backoffice/getRequestedReports',
      cancelRequestedReport: '/api/backoffice/cancelRequestedReport',
      deleteRequestedReport: '/api/backoffice/deleteRequestedReport',
    },


    // getAdminPermissions: '/api/backoffice/getAdminPermissions',

  }
};
